### ISSUE TITLE
PerfMon monitoring integration for Active Directory monitoring

### ISSUE THREAD

**Issue by mgalovich** [newrelic/nri-perfmon#22] opened 2020-09-17 13:24 UTC
Hello,
 
I was told to follow the article below to try to get some Active Directory monitoring, but having issues.
 
https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/perfmon-integration
 
https://github.com/newrelic/nri-perfmon/blob/master/README.md
 
Errors and files that don’t exist.
 
 
Probably going to need to do a screen sharing session with support.
 
Thanks
Mike

**Comment by sschwartzman** [comment] 2020-09-17 14:14
This is an unsupported plugin, so support for which comes through GitHub issues like this one. Can you paste in the  commands you ran and any errors/output you're seeing?

**Comment by mgalovich** [comment] 2020-09-17 14:23
![image](https://user-images.githubusercontent.com/70774952/93484232-47806a80-f8c7-11ea-84c7-b3a88b59630e.png)
<img width="576" alt="NewRelicError" src="https://user-images.githubusercontent.com/70774952/93484330-667efc80-f8c7-11ea-92da-c19a6a2f4785.png">

**Comment by sschwartzman** [comment] 2020-09-17 15:02
Looks like you cloned the repo instead of downloading the release (per the README). Try this link: https://github.com/newrelic/nri-perfmon/releases/latest

**Comment by mgalovich** [comment] 2020-09-17 15:18
Thanks, I'll try that.
Also, do you have any better instructions, then the readme file?
ThanksMike
    On Thursday, September 17, 2020, 10:02:51 AM CDT, Seth Schwartzman <notifications@github.com> wrote:  
 
 


Looks like you cloned the repo instead of downloading the release (per the README). Try this link: https://github.com/newrelic/nri-perfmon/releases/latest

**Comment by sschwartzman** [comment] 2020-09-17 15:23
The instructions are in the README, they're pretty clear and straightforward, from the feedback we've had from other users of it. It has been refined over the years as well (has existed since 2017): https://github.com/newrelic/nri-perfmon/blob/master/README.md#installation

Can you let us know what you perceive as missing from them?

**Comment by mgalovich** [comment] 2020-09-17 16:26
Hi,
it installed properly this time, but not sure where I go from here....
Will the New Relic portal now show more options, when I search on the domain controller I loaded it on?
Mike
    On Thursday, September 17, 2020, 10:23:23 AM CDT, Seth Schwartzman <notifications@github.com> wrote:  
 
 


The instructions are in the README, they're pretty clear and straightforward, from the feedback we've had from other users of it. It has been refined over the years as well (has existed since 2017): https://github.com/newrelic/nri-perfmon/blob/master/README.md#installation

Can you let us know what you perceive as missing from them?

**Comment by sschwartzman** [comment] 2020-09-17 16:43
Like all On-Host Integrations for Infrastructure that are not part of the core product, its events will appear in NRDB and you will need to query for them.  Because this integration could conceivably pick up any counter from Perfmon, we don't have canned dashboards for it.

Here is where you can explore the data:
https://docs.newrelic.com/docs/query-your-data/explore-query-data/data-explorer/introduction-data-explorer

By default, the event types will correspond to the names of those in Perfmon.

What customer are you part of, or is this a personal project? I can ask your associated account team to reach out to help you out.

**Comment by sschwartzman** [comment] 2020-09-17 16:44
Closing issue - integration working as designed.

**Closed by sschwartzman** 2020-09-17 16:44 UTC

**Comment by mgalovich** [comment] 2020-09-17 18:15
I'm with Life Time Fitness. They use New Relic for app monitoring, but asked me to see if it will do any Active Directory monitoring too.
My email there is mgalovich@lt.life, if you can have someone reach out to me, that would be great.
ThanksMike
    On Thursday, September 17, 2020, 11:43:40 AM CDT, Seth Schwartzman <notifications@github.com> wrote:  
 
 


Like all On-Host Integrations for Infrastructure that are not part of the core product, its events will appear in NRDB and you will need to query for them. Because this integration could conceivably pick up any counter from Perfmon, we don't have canned dashboards for it.

Here is where you can explore the data:
https://docs.newrelic.com/docs/query-your-data/explore-query-data/data-explorer/introduction-data-explorer

By default, the event types will correspond to the names of those in Perfmon.

What customer are you part of, or is this a personal project? I can ask your associated account team to reach out to help you out.
