### ISSUE TITLE
Polling interval issue

### ISSUE THREAD

**Issue by Wildpipe** [newrelic/nri-perfmon#7] opened 2019-08-15 13:01 UTC
Hi,

I've got an issue with the polling interval configuration in the file nri-perfmon-definition.yml
I am not able to make the integration respect the interval setting. It doesn't matter if I set the interval value to 10, 60 or 60000 the integration will still continue to poll and report data to NewRelic every 10 seconds. Running nri-perfmon.exe -i 60000 from the command line works though. Appreciate any help I can get in figuring this out.

**Comment by sschwartzman** [comment] 2019-08-15 20:42
hi @Wildpipe can I see your nri-perfmon-definition.yml file?

**Comment by sschwartzman** [comment] 2019-08-15 20:46
Ahh, I know why. That interval is for how often the executible gets executed. Because this is a stateful On-Host Integration, it never returns so that interval is not meaningful. I should document this.

If you want to set the interval, you add -i <interval> to that definition file, like so:

```yaml
#
# New Relic Infrastructure Perfmon Integration
#
name: com.newrelic.perfmon
description: Perfmon On-Host Integration
protocol_version: 1
os: windows
commands:
  metrics:
    command:
      - .\nri-perfmon\nri-perfmon.exe
      - -i <interval_here> 
    prefix: integration/nri-perfmon
    interval: 15
```

**Comment by sschwartzman** [comment] 2019-08-15 20:57
Here's the addition to the README per this Issue: https://github.com/newrelic/nri-perfmon#configuration---command-line-arguments

Let me know if this works for you and then I will close.

**Comment by Wildpipe** [comment] 2019-08-16 08:49
Hi, thanks for the quick help. I am however not able to make it work according to the instructions above.
Using this configuration:
name: com.newrelic.perfmon
description: Perfmon On-Host Integration
protocol_version: 1
os: windows
commands:
  metrics:
    command:
      - .\nri-perfmon\nri-perfmon.exe
      - -i 60
    prefix: integration/nri-perfmon
    interval: 15

Produces the following error:

> time="2019-08-16T08:46:49Z" level=info msg="New Relic Infrastructure Agent version 1.3.5 Creating Service (7.0481ms)"
time="2019-08-16T08:46:49Z" level=info msg="Agent service manager started successfully. (40.0499ms)" service=newrelic-infra
time="2019-08-16T08:46:49Z" level=info msg="New Relic Infrastructure Agent version 1.3.5 Initializing (40.0499ms)"
time="2019-08-16T08:46:50Z" level=info msg="New Relic Infrastructure Agent version 1.3.5 Running (977.0306ms)"
time="2019-08-16T08:46:50Z" level=warning msg="cannot handle plugin output" data prefix=integration/nri-perfmon error="no content to parse" plugin name=nri-perfmon-metrics
time="2019-08-16T08:46:50Z" level=warning msg="cannot handle plugin output" data prefix=integration/nri-perfmon error="invalid character 'c' looking for beginning of value" plugin name=nri-perfmon-metrics
time="2019-08-16T08:46:50Z" level=warning msg="cannot handle plugin output" data prefix=integration/nri-perfmon error="invalid character 'i' looking for beginning of value" plugin name=nri-perfmon-metrics
time="2019-08-16T08:46:50Z" level=warning msg="cannot handle plugin output" data prefix=integration/nri-perfmon error="invalid character ':' in literal null (expecting 'u')" plugin name=nri-perfmon-metrics
time="2019-08-16T08:46:50Z" level=warning msg="cannot handle plugin output" data prefix=integration/nri-perfmon error="invalid character 'v' looking for beginning of value" plugin name=nri-perfmon-metrics
time="2019-08-16T08:46:50Z" level=warning msg="cannot handle plugin output" data prefix=integration/nri-perfmon error="no content to parse" plugin name=nri-perfmon-metrics
time="2019-08-16T08:46:50Z" level=error msg="executing data source" data prefix=integration/nri-perfmon error="exit status 1" plugin name=nri-perfmon-metrics stderr=

>

**Comment by sschwartzman** [comment] 2019-09-11 18:05
It could be that your YAML spacing is off. Have you run that file through a YAML Linter like http://yamllint.com ?

Can you actually drag/drop the config files to this ticket (rather than cut/paste)?

**Comment by Wildpipe** [comment] 2019-09-18 07:13
The YAML linter says the configuration is OK. Attaching config file to thread.
[nri-perfmon-definition.txt](https://github.com/newrelic/nri-perfmon/files/3624916/nri-perfmon-definition.txt)

**Comment by sschwartzman** [comment] 2019-09-18 13:36
Ahh, I see it now, you used seconds instead of ms. Change 60 to 60000.

**Comment by sschwartzman** [comment] 2019-10-04 00:39
Any luck with changing the seconds to ms?

**Comment by sschwartzman** [comment] 2019-10-11 20:23
@Wildpipe I'm going to close this out. If the issue persists after changing from seconds to ms in your entry for `-i`, please let me know here and we can reopen.

**Closed by sschwartzman** 2019-10-11 20:23 UTC

**Comment by sschwartzman** [comment] 2019-11-25 22:12
@Wildpipe I know this is an old issue, but in working this out with another customer, we determined the root cause. Basically, every parameter of the command needs to be on its own line, like this:

```
Hi, thanks for the quick help. I am however not able to make it work according to the instructions above.
Using this configuration:
name: com.newrelic.perfmon
description: Perfmon On-Host Integration
protocol_version: 1
os: windows
commands:
metrics:
command:
- .\nri-perfmon\nri-perfmon.exe
- -i
- 60000
prefix: integration/nri-perfmon
interval: 15
```

If you can, give that a spin and tell me if it works. 

Also, two things:
1. I've updated the nri-perfmon OHI a few times since your issue, I recommend trying it out the [latest release](https://github.com/newrelic/nri-perfmon/releases/tag/0.4.0), which reports log messages to the Windows Event Log.
2. If you ever noticed 'zombie' nri-perfmon processes running on your server after the Infra agent was shut down, it turned out to be a regression in the Infra agent. It has been fixed (personally verified on my Win10 VM) [as of v1.7.6](https://docs.newrelic.com/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-176), I recommend upgrading to that version. 

Thanks,
Seth
