### ISSUE TITLE
Not seeing data in Insights

### ISSUE THREAD

**Issue by solomanyan** [newrelic/nri-perfmon#12] opened 2019-11-01 18:25 UTC
This is almost certainly a case of user error, but I'm trying to use this to monitor individual CPU processor usage (since NewRelic Infrastructure seems to only be able to monitor overall CPU usage rather than individual usage by core). 

As such, I've installed the plugin and am using this as the contents of my config.json:

```
{
	"counterlist": [
		{
			"provider": "PerfOS",
			"category": "Processor",
			"instance": "0",
			"counters": [{
				"counter": "PercentProcessorTime"
			}]
		}
	]
}
```

After restarting the NewRelic service, I checked the logs and saw:
```
time="2019-11-01T14:13:31-04:00" level=info msg="runtime configuration" agentUser="NT AUTHORITY\\SYSTEM" component="New Relic Infrastructure Agent" executablePath="C:\\Program Files\\New Relic\\newrelic-infra\\newrelic-infra.exe" maxProcs=1 pluginDir="[C:\\Program Files\\New Relic\\newrelic-infra\\integrations.d]"
time="2019-11-01T14:13:31-04:00" level=info msg="Checking network connectivity..." component=AgentService service=newrelic-infra
time="2019-11-01T14:13:32-04:00" level=info msg=Initializing component=AgentService elapsedTime=328.6824ms service=newrelic-infra
time="2019-11-01T14:13:32-04:00" level=info msg="New Relic Infrastructure Agent Running" component=AgentService elapsedTime=578.0122ms service=newrelic-infra
time="2019-11-01T14:13:32-04:00" level=info msg=connecting component=Agent
time="2019-11-01T14:13:32-04:00" level=info msg="Agent plugin" plugin=metadata/host_aliases
time="2019-11-01T14:13:32-04:00" level=info msg="Agent plugin" plugin=metadata/attributes
time="2019-11-01T14:13:32-04:00" level=info msg="Agent plugin" plugin=metadata/agent_config
time="2019-11-01T14:13:32-04:00" level=info msg="Agent plugin" plugin=metadata/proxy_config
time="2019-11-01T14:13:32-04:00" level=info msg="Agent plugin" plugin=system/network_interfaces
time="2019-11-01T14:13:32-04:00" level=info msg="Agent plugin" plugin=metadata/system
time="2019-11-01T14:13:32-04:00" level=info msg="Agent plugin" plugin=services/windows_services
time="2019-11-01T14:13:32-04:00" level=info msg="Integration info" arguments="map[include_components:false]" command=packages commandLine="[./nr-winpkg]" env-vars="map[PATH:C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\inetsrv;C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\; VERBOSE:0 INCLUDE_COMPONENTS:false ComSpec:C:\\Windows\\system32\\cmd.exe SystemRoot:C:\\Windows]" instance=windows_packages integration=com.newrelic.winpkg interval=30 labels="map[]" os=windows prefix=packages/windows_programs protocolVersion=1 workingDir="C:\\Program Files\\New Relic\\newrelic-infra\\newrelic-integrations"
time="2019-11-01T14:13:32-04:00" level=info msg="Integration info" arguments="map[]" command=metrics commandLine="[.\\nri-perfmon\\nri-perfmon.exe]" env-vars="map[PATH:C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\inetsrv;C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\; VERBOSE:0 ComSpec:C:\\Windows\\system32\\cmd.exe SystemRoot:C:\\Windows]" instance=nri-perfmon-metrics integration=com.newrelic.perfmon interval=15 labels="map[environment:production]" os=windows prefix=integration/nri-perfmon protocolVersion=1 workingDir="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations"
time="2019-11-01T14:13:32-04:00" level=info msg="Integration health check starting" instance=windows_packages integration=com.newrelic.winpkg prefix=packages/windows_programs working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\newrelic-integrations"
time="2019-11-01T14:13:32-04:00" level=info msg="Integration health check starting" instance=nri-perfmon-metrics integration=com.newrelic.perfmon prefix=integration/nri-perfmon working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations"
time="2019-11-01T14:13:32-04:00" level=info msg="Integration health check finished with success" instance=windows_packages integration=com.newrelic.winpkg prefix=packages/windows_programs working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\newrelic-integrations"
```
which suggests that it should be working correctly. 

Based on my understanding, I should now be able to see this data in NewRelic Insights under the event type "Processor", and the data shown should be the % processor usage for the first CPU core,  right? However, when I check Insights and go to Data Explorer, I'm not seeing any new event types aside from the default Infrastructure ones. 

I assume I'm misunderstanding some step of the process or don't have it configured correctly, so any pointers would really help. Thanks!

**Comment by sschwartzman** [comment] 2019-11-01 19:38
The best thing to do would be to run it at command line and see what it returns, then you'll know what to look for in Insights.

in command prompt:
```
cd \Program Files\New Relic\newrelic-infra\custom-integrations
.\nri-perfmon\nri-perfmon.exe
```

You can paste the result here if you like, or from that you may be able to discern what you need. Let me know either way.

**Comment by sschwartzman** [comment] 2019-11-01 19:54
Also, you may want to leave 'instance' out entirely. With perf counters, if no instance is provided, it will poll all instances and keep them separate from one another, using the "name" attribute in each event to specify the instance, so you can facet on 'name' and see all of your cores at once!

**Comment by sschwartzman** [comment] 2019-11-01 19:59
I tried your counter file and it's valid. With the instance: 0 left in, I see this:
```
{
  "name": "DESKTOP-KHVRAET",
  "protocol_version": "1",
  "integration_version": "0.1.0",
  "events": [],
  "inventory": {},
  "metrics": [
    {
      "event_type": "Processor",
      "Name": "0",
      "PercentProcessorTime": 64
    }
  ]
}
```
and when I take out the "instance" line I see this:
```
{
  "name": "DESKTOP-KHVRAET",
  "protocol_version": "1",
  "integration_version": "0.1.0",
  "events": [],
  "inventory": {},
  "metrics": [
    {
      "event_type": "Processor",
      "Name": "_Total",
      "PercentProcessorTime": 32
    },
    {
      "event_type": "Processor",
      "Name": "0",
      "PercentProcessorTime": 0
    },
    {
      "event_type": "Processor",
      "Name": "1",
      "PercentProcessorTime": 64
    }
  ]
}
```

**Comment by solomanyan** [comment] 2019-11-04 17:52
Oh wow, I didn't expect such a prompt and detailed response - thank you for the assistance! 

I tried running it in command prompt and it looks like it's returning the correct data, so it should be working correctly. However, I'm not seeing any of data in NewRelic Insights - I'm unsure if there's any additional step I missed in order to link it, or if I'm just not looking it up correctly. I had assumed that this was built-in and Insights would automatically track it - is this correct, or do I need to implement a custom tracker to import the data into Insights? If it's already built-in, then are there any queries/settings I need in Insights in order to view the data?

**Comment by sschwartzman** [comment] 2019-11-04 21:49
If this is being executed by the Infrastructure Agent, then there is nothing you should need to do - Is the Infra agent running properly on that host?

If it's failing, you can try turning logging on for the infra agent to see if it's failing, like so: https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/troubleshooting/generate-logs-troubleshooting-infrastructure

**Comment by solomanyan** [comment] 2019-11-05 14:51
Yep, the Infra agent is working fine - I'm able to view data from this host in both the Infrastructure page and in Insights. The Data Explorer in Insights only shows the default Infrastructure events, though, and not the perfmon events: https://i.imgur.com/NsjQbm7.png

I checked the logfiles and the base logs don't show any errors or issues. I enabled verbose logging to see if that might help, but there's so much in the log that I'm afraid I can't really tell if there is an issue or not. One section I noticed which might be of concern:

```
time="2019-11-05T09:40:52-05:00" level=debug msg="metrics post succeeded" component=MetricsIngestSender postCount=3
time="2019-11-05T09:40:53-05:00" level=debug msg="Integration payload" instance=nri-perfmon-metrics integration=com.newrelic.perfmon payload="{\"name\":\"931713-IAD3-AD2\",\"protocol_version\":\"1\",\"integration_version\":\"0.1.0\",\"events\":[],\"inventory\":{},\"metrics\":[{\"event_type\":\"Processor\",\"Name\":\"_Total\",\"PercentProcessorTime\":16},{\"event_type\":\"Processor\",\"Name\":\"0\",\"PercentProcessorTime\":11},{\"event_type\":\"Processor\",\"Name\":\"1\",\"PercentProcessorTime\":0},{\"event_type\":\"Processor\",\"Name\":\"2\",\"PercentProcessorTime\":0},{\"event_type\":\"Processor\",\"Name\":\"3\",\"PercentProcessorTime\":0},{\"event_type\":\"Processor\",\"Name\":\"4\",\"PercentProcessorTime\":58},{\"event_type\":\"Processor\",\"Name\":\"5\",\"PercentProcessorTime\":11},{\"event_type\":\"Processor\",\"Name\":\"6\",\"PercentProcessorTime\":35},{\"event_type\":\"Processor\",\"Name\":\"7\",\"PercentProcessorTime\":17}]}" prefix=integration/nri-perfmon working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations"
time="2019-11-05T09:40:53-05:00" level=debug msg="still waiting on plugins" component=Agent pluginIds="[services/windows_services integration/nri-perfmon]"
time="2019-11-05T09:40:53-05:00" level=debug msg="Sending events to metrics-ingest" component=MetricsIngestSender key=5027484144858523643 numEvents=10 postCount=4 timestamps="[2019-11-05 09:40:52 -0500 EST 2019-11-05 09:40:53 -0500 EST]"
time="2019-11-05T09:40:53-05:00" level=debug msg="preparing metrics post" component=MetricsIngestSender postCount=4
time="2019-11-05T09:40:53-05:00" level=debug msg="metrics post succeeded" component=MetricsIngestSender postCount=4
time="2019-11-05T09:40:54-05:00" level=debug msg="still waiting on plugins" component=Agent pluginIds="[services/windows_services integration/nri-perfmon]"
time="2019-11-05T09:40:55-05:00" level=debug msg="still waiting on plugins" component=Agent pluginIds="[services/windows_services integration/nri-perfmon]"
time="2019-11-05T09:40:56-05:00" level=debug msg="still waiting on plugins" component=Agent pluginIds="[services/windows_services integration/nri-perfmon]"
time="2019-11-05T09:40:57-05:00" level=debug msg="still waiting on plugins" component=Agent pluginIds="[services/windows_services integration/nri-perfmon]"
```

**Comment by sschwartzman** [comment] 2019-11-06 06:24
Yeah, all of what's there looks perfectly fine and what we'd expect - the "still waiting on plugins" messages are benign because the Perfmon agent doesn't stop running. Can you email me (seth at newrelic dot com) your account ID so I can take a look at the data there?

**Comment by sschwartzman** [comment] 2019-11-12 14:21
Closing issue - root cause is that the user's account is in the "Essentials" subscription level for Infrastructure, which does not collect data from on-host integrations.

**Closed by sschwartzman** 2019-11-12 14:21 UTC
